### ISSUE TITLE
$href undefined

### ISSUE THREAD

**Issue by paulerickson** [myuw-web-components/myuw-drawer#11]
#10 makes unsafe reference to variables like `this.$href` that aren't defined until the component is connected, causing exceptions to be thrown when attributes are set:
Example https://kbtest.wisc.edu/kb-site/
```
Uncaught TypeError: Cannot read property ‘setAttribute’ of undefined
   at HTMLElement.updateComponent (myuw-drawer.min.mjs?module:31)
   at HTMLElement.attributeChangedCallback (myuw-drawer.min.mjs?module:26)
   at myuw-drawer.min.mjs?module:37
```

**Comment by thevoiceofzeke** [comment]
Addressed by #21
